### ISSUE TITLE
post-meta gets flushed every other save when using memcached

### ISSUE THREAD

**Issue by aristath** [SiteGround/sg-cachepress#13]
If Memcached is enabled and I edit a post's post-meta (custom field), then on 1st save things work.
BUT if I save again the post, the custom-fields are reset.

**Comment by ioelada** [comment]
i have the same, just in my case is not save first time, and custom fileds are reset.

**Comment by ivanyord** [comment]
Hello guys. We have fixed a similar issue in our latest release (2.3.11). If you are still experiencing any issues, can someone of you open a ticket with a test case (it's better to be a test site so we can review it and make changes on it) and provide me with a ticket number to check it?

**Comment by ioelada** [comment]
hi, i allready have a ticket on siteground (1958717) and 2.3.11 version. and is the same

**Comment by ivanyord** [comment]
Hello. Just wanted to mention that the issue has been identified and we are working on a solution. The issue will be solved in some of the upcoming new releases of the plugin.

**Comment by aristath** [comment]
@ivanyord thanks for the update!
Most times identifying the issue is the most difficult part 👍

**Comment by ioelada** [comment]
i don't know if you update the plugin, but the issue still is. not in the same way.
now the only field what reset on save is "Page Content Padding" (in fusion page option).
but if i set value every time when i save the page is fine. but it is very annoyed to do that on every page save.
thanks
