### ISSUE TITLE
"SG Cachepress" Blue overwriting Wordpress default button colour

### ISSUE THREAD

**Issue by tjhole** [SiteGround/sg-cachepress#14]
Small quirk of the 3.0 upgrade.

I have found the plugin injecting CSS for **.wp-core-ui .button-primary** on every page.

This results in the Publish button switching to the same #49587c colour because of the "#49587c**!important**"

![screen shot 2017-02-01 at 16 58 23](https://cloud.githubusercontent.com/assets/2581755/22517100/ef7e9c52-e89f-11e6-8607-c047436eadac.png)

This is a non-breaking issue but I have a few clients on SG and this has resulted in a few confused questions from them today

**Comment by pandjarov** [comment]
Fixed in 3.0.3
