### ISSUE TITLE
Force HTTPS prevent preserving og:url

### ISSUE THREAD

**Issue by orjhor** [SiteGround/sg-cachepress#15]
When moving from HTTP to HTTPS it is ofted needed to preserve Facebook likes for an URL. This is done by ensuring that the `<meta property="og:url" content="http://www.someurl.no" />` tag is in place in the HTML rendered. 
However, when the "Force HTTPS" is enabled in the sg-cachepress plugin it is replacing all instances of HTTP with HTTPS in the HTML rendered. This includes the og:url element, thus meaning that we cannot both preserve Facebook-likes and force HTTPS simultaneously. 

As a very temporary fix I've added these lines directly in the end of the **replace_insecure_links** -function, but this is _not_ a preferred fix:

```
public static function replace_insecure_links($str) {

...

$str = str_replace('og:url" content="https://', 'og:url" content="http://', $str); 
$str = str_replace('rel="canonical" href="https://', 'rel="canonical" href="http://', $str); 

return apply_filters("rsssl_fixer_output", $str);
```

Is there any way to white-list tags to prevent them from being forced to HTTPS?

**Comment by pandjarov** [comment]
I am afraid there's nothing we can do about this since it will cause insecure content warning if not rewritten.
