### ISSUE TITLE
Minimum PHP version?

### ISSUE THREAD

**Issue by GaryJones** [SiteGround/sg-cachepress#2]
The shared hosting cPanel PHP version manager has the lowest version at 5.3.29. Is there any setup where this plugin could reasonably be expected to work, that has a lower version of PHP?

i.e. could namespaces be introduced?

**Comment by pandjarov** [comment]
5.3 is listed as minimum required version.

**Comment by grappler** [comment]
Actually in the readme is list as PHP 5.5. 🤷‍♂️
