### ISSUE TITLE
Autoloader

### ISSUE THREAD

**Issue by GaryJones** [SiteGround/sg-cachepress#3]
The main plugin file currently loads six class files. Now a huge amount in the grand scheme of things, How about an autoloader? If #2 is successful, a PSR-4 compatible autoloader?

The initial structure of code is such that all of the class files are required. For instance, `class-sg-cachepress-admin.php` is required, and `SG_CachePress_Admin` is instantiated, for all front-end and admin requests.

**Comment by GaryJones** [comment]
Another benefit of autoloading would be if there was an early check to see if the site was on SG, and if not, don't bother loading up the rest of the functionality that won't generally work anyway.

**Comment by pandjarov** [comment]
Pull requests are welcome :)

**Comment by GaryJones** [comment]
> Pull requests are welcome :)

Well, yes, but knowing that we can definitely use PHP 5.3 features would help.

**Comment by aristath** [comment]
> Well, yes, but knowing that we can definitely use PHP 5.3 features would help.

Well yeah, 5.3 would help... But you can still write an autoloader for 5.2... 😄

**Comment by GaryJones** [comment]
Of course, but knowing the minimum required level of PHP that a bit of code needs to support, should be a starting point for most projects.

**Comment by grappler** [comment]
> Pull requests are welcome :)

Sure, but are they going to be merged. I have a PR open since June with no response.

**Comment by GaryJones** [comment]
> Sure, but are they going to be merged. I have a PR open since June with no response.

I've got 6 issues open going back to April 2016, and this is the only one with any sort of response.
