### ISSUE TITLE
object-cache.php not updated when changing php5.6

### ISSUE THREAD

**Issue by mircobabini** [SiteGround/sg-cachepress#31]
PHP5.6 needs the object-cache.php with Memcache (without d) implementation.
PHP7.0 needs the object-cache.php with Memcached implementation.

Setup: PHP5.6 turned on.
I activate Memcached through the plugin, object-cache.php is installed.

Then I change PHP version to 7.0 through .htaccess.
object-cache.php IS NOT UPDATED, so it's not really working.

**Comment by Stoyan0v** [comment]
Closing this ticket, because it's related to older version of the plugin. Please update to latest version and open an issue if the problem still exists.
