### ISSUE TITLE
Could not disable Memcache!

### ISSUE THREAD

**Issue by mircobabini** [SiteGround/sg-cachepress#32]
Sometimes wp shows memcached disabled, but when you try to enable the message you see is: Could not disable Memcache!

That's because object-cache.php is missing. Please, detect when object-cache.php is missing and show something to correct the misbehaviour or automatically turn off memcached; so it would be possible to turn it on again, without touching the file system manually.

Actually, to solve:
1. Create object-cache.php (empty)
2. Try again to turn off (it deletes the object-cache.php)
3. Now you can turn in on

**Comment by Stoyan0v** [comment]
Closing this ticket, because it's related to older version of the plugin. Please update to latest version and open an issue if the problem still exists.
