### ISSUE TITLE
WP-CLI fails during wp_redirect()

### ISSUE THREAD

**Issue by afragen** [SiteGround/sg-cachepress#38]
`class-sg-cachepress-multisite.php` has an error when running `$this->force_https()` under WP-CLI.

This apparently is not a new issue. https://github.com/johngodley/redirection/issues/222

The _real_ solution is to add a check to `php_sapi_name()` or a check of `WP_CLI` in `force_https()`.

I've created a fix and will submit a PR. In testing it works for me. I'm just creating an issue for the PR.

**Comment by afragen** [comment]
Issue referenced here too. https://wordpress.org/support/topic/_serverhttp_host-is-undefined-when-access-site-via-wp-cli/

**Comment by afragen** [comment]
https://core.trac.wordpress.org/ticket/44429

**Comment by Stoyan0v** [comment]
Closing this ticket, because it's related to older version of the plugin. Please update to latest version and open an issue if the problem still exists.
