### ISSUE TITLE
Can't optimize existing images when using the KB's "real cron job".

### ISSUE THREAD

**Issue by justlevine** [SiteGround/sg-cachepress#41]
**Issue**
The option to optimize existing images is disabled when the internal WordPress cron job is disabled in lieu of a 'real cron job'.

As you know, the built-in `wp-cron.php` is extremely unreliable, and problematic. From the [Knowledgebase](https://www.siteground.com/tutorials/wordpress/real-cron-job/):

> [T]his file may become target of a DOS attack, or caching plugins can interfere with its execution which can cause either a lot of server load or the scheduled tasks may not execute properly and timely. This is why, you can substitute this constant file execution with a real cron job.

**Current Behavior**
The plugin detects `define('DISABLE_WP_CRON', true)`, and turns off the feature.

**Expected Behavior**
SG Optimizer should check to see if a manual cron job is set up as described in the [above tutorial](https://www.siteground.com/tutorials/wordpress/real-cron-job/): 
`wget -q -O - http://yourdomain.com/wp-cron.php?doing_wp_cron >/dev/null 2>&1`

Alternatively, if there isn't a way for wordpress to detect manual cron-jobs, an option should exist ( in the plugin settings or defined in `wp-config.php` if you're worried about less-technically apt users) to enable Existing Image Optimization regardless.

**Comment by Stoyan0v** [comment]
We've fixed this in version 5.0.6. Please update and let us know if the issue still exists.

**Comment by justlevine** [comment]
Now that you mention it, it does.
Didn't realize, because the new option to 'ignore this message' was mixed within the paragraph text. You might want to make it more actionable, so it doesn't seem like another kb link.
